### ISSUE TITLE
How much memory does the program need?

### ISSUE THREAD

**Issue by TaiJuWu** [HSLCY/GlossBERT#5]
Hello,
Would you tell me how much memory is needed for training GlossBERT using your example setting?
while I train the model, it always shows RuntimeError: CUDA out of memory.
My gpu is 1080Ti 10G.

error:
Traceback (most recent call last):
  File "run_classifier_WSD_sent.py", line 706, in <module>
    main()
  File "run_classifier_WSD_sent.py", line 520, in main
    logits = model(input_ids=input_ids, token_type_ids=segment_ids, attention_mask=input_mask, labels=None)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 59, in _worker
    output = module(*input, **kwargs)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/GlossBERT/modeling.py", line 972, in forward
    _, pooled_output = self.bert(input_ids, token_type_ids, attention_mask, output_all_encoded_layers=False)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/GlossBERT/modeling.py", line 716, in forward
    output_all_encoded_layers=output_all_encoded_layers)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/GlossBERT/modeling.py", line 395, in forward
    hidden_states = layer_module(hidden_states, attention_mask)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/GlossBERT/modeling.py", line 380, in forward
    attention_output = self.attention(hidden_states, attention_mask)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/GlossBERT/modeling.py", line 338, in forward
    self_output = self.self(input_tensor, attention_mask)
  File "/home/nlplab/tjwu/anaconda3/envs/GlossBERT/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nlplab/tjwu/GlossBERT/modeling.py", line 298, in forward
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 10.92 GiB total capacity; 10.20 GiB already allocated; 23.38 MiB free; 30.57 MiB cached)

**Comment by HSLCY** [comment]
Hello, in my example setting, for `train_batch_size = 64` need 4*16G gpus. You can try less gpu memory by changing the batchsize (like 32, 16).
